"""SQL types from schema/types/sql.graphql."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .scalars import Int64


class SQLExecResult(BaseModel):
    """Result of a SQL exec from schema/types/sql.graphql.

    The number of rows affected by the query, usually an UPDATE, INSERT, or DELETE.
    Not all queries or databases support this feature.

    The integer generated by the database in response to a command.
    Typically this will be from an "auto increment" column when inserting a new row.
    Not all databases support this feature, and the syntax of such statements varies.
    """

    rows_affected: Int64 | None = None  # Int64
    last_insert_id: Int64 | None = None  # Int64


class SQLQueryResult(BaseModel):
    """Result of a SQL query from schema/types/sql.graphql.

    The column names, in the order they appear in the result set,
    and the returned rows.
    """

    columns: list[str]  # [String!]!
    rows: list[list[Any]]  # [[Any]!]!
